server:
  port: 11080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

setting:
  apiKey: Bearer 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

wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: wxebb309d70bca7c14 # 第一个公众号的appid
        secret: c1ba9de4bc9a31f7a67cdf8308b1b03c # 公众号的appsecret
        token: chatgpt123123 # 接口配置里的Token值
        aesKey: AwKGQNsOAh0jaEKDVOMNGNUeUsaZaoJpP08tEylNWFn # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111